### ISSUE TITLE
How to train with GPUs?

### ISSUE THREAD

**Issue by wafuuri** [Simeonedef/music_gen_deep_learning#1]
Hi, a little question about how to train the models by GPU but not CPU? Training by CPU is too slow to get a result. Is there any configuration that can change this?

**Comment by Simeonedef** [comment]
This will depend on your installation of tensorflow

If you have tensorflow-gpu installed then it will train on gpu, otherwise cpu :)

Although as a sidenote, LSTMs are usually not the ones who benefit the most from GPU speedup because they cannot be parallelized that much
